name: Deploy Playwright

env:
  image_name: fyl080801/llama-factory

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # 从 GitHub 拉取代码
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          repository: hiyouga/LLaMA-Factory

      # 登录到 GitHub Container Registry (ghcr.io)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -f ./docker/docker-cuda/Dockerfile \
            --build-arg INSTALL_BNB=false \
            --build-arg INSTALL_VLLM=false \
            --build-arg INSTALL_DEEPSPEED=false \
            --build-arg INSTALL_FLASHATTN=false \
            --build-arg PIP_INDEX=https://pypi.org/simple \
            -t ghcr.io/${{ env.image_name }}:latest .

      # 推送 Docker 镜像到 GitHub Container Registry
      - name: Push Docker image
        run: docker push ghcr.io/${{ env.image_name }}:latest
